### ISSUE TITLE
is broken for play 2.6?

### ISSUE THREAD

**Issue by klclee** [kaliber-scala/play-s3#79]
Hi, trying to use this in play 2.6.0 I am getting the following:

```
booking     | java.lang.NoClassDefFoundError: play/api/libs/ws/WSRequest$class
booking     | 	at fly.play.aws.AwsRequestHolder.<init>(AwsRequestHolder.scala:10)
booking     | 	at fly.play.s3.S3Client.resourceRequest(S3Client.scala:13)
booking     | 	at fly.play.s3.S3.put(S3.scala:83)
booking     | 	at fly.play.s3.Bucket.add(Bucket.scala:118)
booking     | 	at fly.play.s3.Bucket$$anonfun$$plus$1.apply(Bucket.scala:111)
booking     | 	at fly.play.s3.Bucket$$anonfun$$plus$1.apply(Bucket.scala:111)
booking     | 	at services.BookingFileService.uploadFile(BookingFileService.scala:27)
booking     | 	at controllers.BookingFileController$$anonfun$uploadFile$1$$anonfun$1.apply(BookingFileController.scala:56)
booking     | 	at controllers.BookingFileController$$anonfun$uploadFile$1$$anonfun$1.apply(BookingFileController.scala:52)
booking     | 	at scala.Option.map(Option.scala:146)
booking     | Caused by: java.lang.ClassNotFoundException: play.api.libs.ws.WSRequest$class
booking     | 	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
booking     | 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
booking     | 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
booking     | 	at fly.play.aws.AwsRequestHolder.<init>(AwsRequestHolder.scala:10)
booking     | 	at fly.play.s3.S3Client.resourceRequest(S3Client.scala:13)
booking     | 	at fly.play.s3.S3.put(S3.scala:83)
booking     | 	at fly.play.s3.Bucket.add(Bucket.scala:118)
booking     | 	at fly.play.s3.Bucket$$anonfun$$plus$1.apply(Bucket.scala:111)
booking     | 	at fly.play.s3.Bucket$$anonfun$$plus$1.apply(Bucket.scala:111)
booking     | 	at services.BookingFileService.uploadFile(BookingFileService.scala:27)
```

**Comment by EECOLOR** [comment]
It has not been compiled against 2.6, you're welcome to create a pull request
